version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: 'lucas-sandery'
    ports:
      - 80:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root