version: '3.1'

volumes:
  postgre:

networks:
  a-system-network:
    driver: bridge

services:

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: 'lucas-sandery'
      POSTGRES_HOST: postgres-server
    networks:
      - a-system-network
    ports:
      - 80:8080
    links:
      - postgres:postgres-server

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - a-system-network
    ports:
      - 5432:5432
    volumes:
      - postgre:/var/lib/postgresql/data