version: '3.1'

volumes:
  postgres:
  zookeeper:
  kafka:
  kafka-ui:

networks:
  a-system-network:
    driver: bridge

services:

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: 'lucas-sandery'
      POSTGRES_HOST: postgres-server
    networks:
      - a-system-network
    ports:
      - 80:8080
    links:
      - postgres:postgres-server

  postgres:
    image: postgres
    container_name: a-system-postgres
    environment:
      POSTGRES_DB: a-system
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - a-system-network
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  zookeeper:
    networks:
      - a-system-network
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - a-system-network
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
    volumes:
      - kafka:/etc/kafka/secrets
      - kafka:/var/lib/kafka/data

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8082:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true